# -*- coding: utf-8 -*-
"""Data_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XX5ZW7huBMVpNDr2v67DklDYPrD0ysYH

# **Práctica 3: Data Visualization**

Cargamos el dataset
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Video_Games_Sales_Cleaned.csv")

"""Configuración estética de las gráficas"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

"""**Histograma de ventas globales**"""

plt.figure(figsize=(8,6))
plt.hist(df["Global_Sales"], bins=50, color="skyblue", edgecolor="black")
plt.title("Distribución de Ventas Globales")
plt.xlabel("Ventas (millones)")
plt.ylabel("Frecuencia")
plt.show()

"""**Boxplot de ventas por género**"""

plt.figure(figsize=(12,6))
sns.boxplot(x="Genre", y="Global_Sales", data=df)
plt.xticks(rotation=45)
plt.title("Ventas Globales por Género (Boxplot)")
plt.show()

"""**Pie chart de participación por plataforma (Top 5)**"""

platform_sales = df.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False).head(5)

plt.figure(figsize=(8,8))
plt.pie(platform_sales, labels=platform_sales.index, autopct='%1.1f%%', startangle=140)
plt.title("Top 5 Plataformas por Ventas Globales")
plt.show()

"""**Gráfico de dispersión (ventas NA vs EU)**"""

plt.figure(figsize=(8,6))
plt.scatter(df["NA_Sales"], df["EU_Sales"], alpha=0.5)
plt.title("Relación entre ventas en NA y EU")
plt.xlabel("NA_Sales (millones)")
plt.ylabel("EU_Sales (millones)")
plt.show()

"""**Gráfico de barras (ventas por año)**"""

year_sales = df.groupby("Year")["Global_Sales"].sum()

plt.figure(figsize=(12,6))
year_sales.plot(kind="bar", color="teal")
plt.title("Ventas Globales por Año")
plt.xlabel("Año de Lanzamiento")
plt.ylabel("Ventas (millones)")
plt.show()

"""**Histogramas de ventas por región**"""

num_vars = ["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]

for col in num_vars:
    plt.figure(figsize=(8,6))
    plt.hist(df[col], bins=40, edgecolor="black", alpha=0.7)
    plt.title(f"Histograma de {col}")
    plt.xlabel(col)
    plt.ylabel("Frecuencia")
    plt.show()

"""**Gráficas de ventas globales por género**"""

# Ventas por género
df.groupby("Genre")["Global_Sales"].sum().sort_values().plot(kind="barh", figsize=(10,6))
plt.title("Ventas globales por género")
plt.xlabel("Ventas en millones")
plt.show()

"""**Gráfico de ventas por plataforma**"""

df.groupby("Platform")["Global_Sales"].sum().sort_values().plot(kind="barh", figsize=(10,8))
plt.title("Ventas globales por plataforma")
plt.xlabel("Ventas en millones")
plt.show()

"""**Gráfico de tendencia de ventas por año**"""

df.groupby("Year")["Global_Sales"].sum().plot(kind="line", figsize=(10,6))
plt.title("Tendencia de ventas globales por año")
plt.ylabel("Ventas en millones")
plt.xlabel("Año de lanzamiento")
plt.show()