# -*- coding: utf-8 -*-
"""Text_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p53rE4cxZYyB-PTJpUN4tCEoMxspF4nz

# **Práctica 9: Text analysis**

Cargamos el dataset, para esta práctica trabajaremos con las columnas "Plataform", "Genre" "Name"

# Plataform
"""

import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Video_Games_Sales_Cleaned.csv")

df.head()

"""Creamos nuestro texto base"""

# Convertir todos los nombres de plataformas en una sola cadena
text = " ".join(str(platform) for platform in df['Platform'])

"""Generamos la nube de palabras"""

wordcloud = WordCloud(
    width=1000,
    height=600,
    background_color='white',
    colormap='viridis',
    collocations=False
).generate(text)

"""Mostramos la nube de palabras generada anteriormente"""

plt.figure(figsize=(12, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Nube de Palabras de Plataformas de Videojuegos", fontsize=16)
plt.show()

"""El resultado esperado es una nube de palabras colorida donde las plataformas como PS2, X360, PS3, Wii, DS y PC son las que mas predominan a simple vista.

# Genre

Creamos el texto base para género
"""

# Unir todos los géneros en una sola cadena de texto
text_genre = " ".join(str(genre) for genre in df['Genre'])

"""Generar la nube de palabras y mostrarla en pantalla"""

# Crear la nube de palabras de géneros
wordcloud_genre = WordCloud(
    width=1000,
    height=600,
    background_color='white',
    colormap='plasma',
    collocations=False
).generate(text_genre)

plt.figure(figsize=(12, 8))
plt.imshow(wordcloud_genre, interpolation='bilinear')
plt.axis('off')
plt.title("Nube de Palabras de Géneros de Videojuegos", fontsize=16)
plt.show()

"""El resultado es una nube donde géneros como Action o Sports están en letras más grandes según su frecuencia en el dataset

# Name

Combinamos todos los nombres en un solo texto
"""

# Unir todos los nombres de juegos en una sola cadena
text = " ".join(str(name) for name in df['Name'])

"""Generamos la nube de palabras y la mostramos en pantalla"""

wordcloud = WordCloud(
    width=1400,
    height=800,
    background_color='white',
    colormap='magma',
    stopwords={'the','and','of','a','to','in','for','on','with','by','&'},
    max_words=200
).generate(text)

plt.figure(figsize=(14, 10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Nube de Palabras de Nombres de Videojuegos", fontsize=18)
plt.show()

"""La nube muestra palabras comunes como "Game", "Adventure" o "II (dos)"
"""