# -*- coding: utf-8 -*-
"""Text_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p53rE4cxZYyB-PTJpUN4tCEoMxspF4nz

# **Práctica 9: Text analysis**

Cargamos el dataset, para esta práctica trabajaremos con la columna "Plataform"
"""

import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Video_Games_Sales_Cleaned.csv")

df.head()

"""Creamos nuestro texto base"""

# Convertir todos los nombres de plataformas en una sola cadena
text = " ".join(str(platform) for platform in df['Platform'])

"""Generamos la nube de palabras"""

wordcloud = WordCloud(
    width=1000,
    height=600,
    background_color='white',
    colormap='viridis',
    collocations=False
).generate(text)

"""Mostramos la nube de palabras generada anteriormente"""

plt.figure(figsize=(12, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Nube de Palabras de Plataformas de Videojuegos", fontsize=16)
plt.show()

"""El resultado esperado es una nube de palabras colorida donde las plataformas como PS2, X360, PS3, Wii, DS y PC son las que mas predominan a simple vista.

# Uso de texto alternativo
Para realizar esta parte de la práctica, haremos uso de la libreria word cloud, usaremos un texto extraido de la pagina de wikipedia que trata acerca del tema de Text Mining. El texto se encuentra almacenado en el archivo textAnalysis.txt.
"""

# Cargar el archivo
with open("/content/textAnalysis.txt", "r", encoding="utf-8") as file:
    text_data = file.read()

"""Creamos la nube de palabras, la generamos y mostramos en pantalla"""

wordcloud = WordCloud(
    width=1200,
    height=800,
    background_color='white',
    colormap='inferno',
    stopwords={'the', 'and', 'of', 'to', 'in', 'for', 'is', 'a', 'on', 'as', 'by', 'an', 'be', 'with', 'that'},
    max_words=200
).generate(text_data)

plt.figure(figsize=(14, 9))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Nube de Palabras del Texto 'textAnalysis.txt'", fontsize=18)
plt.show()

"""El resultado final es una nube de palabras, donde las mas comunes a simple vista son "text, mining, analysis, information, data" por ejemplo."""