# -*- coding: utf-8 -*-
"""Linear_Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18x5Gg_6TAq4m5tLjBdVMqYnlP8xZgqGY

# **Práctica 5: Linear Models and correlation**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

df = pd.read_csv("Video_Games_Sales_Cleaned.csv")
df

"""# Correlación entre ventas regionales y globales
Calculamos la matriz de correlación y graficamos
"""

# matriz de correlación
corr = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales", "Global_Sales"]].corr()

print("Matriz de correlación:")
print(corr)

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlación entre ventas regionales y globales")
plt.show()

"""# Modelo Lineal Simple
Elegimos nuestras variables (JP_Sales como predictor y Global_Sales somo dependiente)
"""

X = df[["JP_Sales"]]
y = df["Global_Sales"]

# Ajustar modelo
model_simple = LinearRegression()
model_simple.fit(X, y)

"""Hacemos las predicciones y obtenemos el R2 score"""

y_pred_simple = model_simple.predict(X)

r2_simple = r2_score(y, y_pred_simple)

print("Modelo simple: Global_Sales ~ JP_Sales")
print(f"Ecuación: Global_Sales = {model_simple.intercept_:.3f} + {model_simple.coef_[0]:.3f} * JP_Sales")
print(f"R2 = {r2_simple:.4f}")

"""Graficamos"""

plt.figure(figsize=(8,6))
sns.scatterplot(x="JP_Sales", y="Global_Sales", data=df, hue="Genre", alpha=0.7)
plt.plot(df["JP_Sales"], y_pred_simple, color="black", linewidth=2, label="Línea de regresión")
plt.xlabel("JP_Sales")
plt.ylabel("Global_Sales")
plt.title("Modelo lineal simple (coloreado por género)")
plt.legend()
plt.show()

"""# Modelo Lineal Múltiple (todas las regiones)
Ahora tomaremos en cuenta todas las regiones para la variable predictor
"""

X_multi = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]]
y = df["Global_Sales"]

model_multi = LinearRegression()
model_multi.fit(X_multi, y)

y_pred_multi = model_multi.predict(X_multi)

r2_multi = r2_score(y, y_pred_multi)

print("Modelo múltiple: Global_Sales ~ NA_Sales + EU_Sales + JP_Sales + Other_Sales")
print("Intercepto:", round(model_multi.intercept_, 3))
print("Coeficientes:", dict(zip(X_multi.columns, model_multi.coef_.round(3))))
print(f"R2 = {r2_multi:.6f}")

"""Como podemos ver el valor de R2 es muy cercano a 1, esto se debe a que "Global_Sales" es la suma de todas las columnas (regiones)

Gráfica para el modelo lineal múltiple
"""

plt.figure(figsize=(8,6))
plt.scatter(y, y_pred_multi, alpha=0.5)
plt.xlabel("Global_Sales (real)")
plt.ylabel("Global_Sales (predicho)")
plt.title("Modelo múltiple: Ventas reales vs predichas")
plt.plot([0, max(y)], [0, max(y)], color="red", linestyle="--")
plt.show()

"""# Gráfico con residuales
Utilizamos este grafico para ver si hay errores (lo ideal es que los puntos estén cerca de 0)
"""

residuals = y - y_pred_multi
plt.figure(figsize=(10,6))
sns.scatterplot(x=y, y=residuals, alpha=0.5)
plt.axhline(0, color="red", linestyle="--")
plt.xlabel("Ventas Reales")
plt.ylabel("Residual (Real - Predicho)")
plt.title("Residual Plot")
plt.show()