# -*- coding: utf-8 -*-
"""Data_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zt8ZlZd0kur0wU1bhm8Po9EBchOvvs-f

# **Práctica 6: Data classification**
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Cargar dataset limpio
df = pd.read_csv("/content/Video_Games_Sales_Cleaned.csv")

df

"""# Creación de la variable de clasificación
Creamos una nueva columna llamada "Sales_level" que clasifica los juegos por sus ventas globales
"""

# Clasificar las ventas globales en tres niveles
df["Sales_Level"] = pd.cut(
    df["Global_Sales"],
    bins = [-0.01, 0.2, 1, df["Global_Sales"].max()],
    labels=["Bajas", "Medias", "Altas"]
)

df["Sales_Level"].value_counts()

"""# Preparar las variables para el modelos
Vamos a utilizar las ventas regionales como características predictoras
"""

# entradas
X = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]]

# salida
y = df["Sales_Level"]

"""Dividir en conjuntos de entrenamiento y prueba, luego estandarizamos los datos"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Estandarizar los datos
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""# Crear y entrenar el modelo KNN
Creamos el modelo KNN con k=5 vecinos, lo entrenamos con los datos estandarizados y predecimos con los datos de prueba

"""

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

# Predicciones
y_pred = knn.predict(X_test_scaled)

"""# Evaluamos nuestro modelo
Mostramos la matriz de confusión y la visualizamos para hacer una pequeña tabla
"""

# Matriz de confusión
cm = confusion_matrix(y_test, y_pred)

# Visualización
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=knn.classes_, yticklabels=knn.classes_)
plt.xlabel("Predicción")
plt.ylabel("Real")
plt.title("Matriz de Confusión - KNN Clasificación de Ventas")
plt.show()

# Reporte de clasificación
print("\nReporte de Clasificación:\n")
print(classification_report(y_test, y_pred))

"""Ahora probamos con diferentes valores de 'k' para encontrar la mejor"""

from sklearn.metrics import accuracy_score

k_values = range(1, 21)
scores = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    y_pred_k = knn.predict(X_test_scaled)
    scores.append(accuracy_score(y_test, y_pred_k))

# Encontrar el mejor k
best_k = scores.index(max(scores)) + 1
print(f"El mejor valor de k es: {best_k}, con una precisión de {max(scores):.4f}")


plt.figure(figsize=(8,5))
plt.plot(k_values, scores, marker="o", color="blue")
plt.title("Precisión del Modelo KNN vs Número de Vecinos (k)")
plt.xlabel("Número de Vecinos (k)")
plt.ylabel("Precisión")
plt.show()

"""# Scatter plot: Predicción vs Valor Real"""

import matplotlib.pyplot as plt
import numpy as np

best_k = scores.index(max(scores)) + 1
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train, y_train)
y_pred = knn_best.predict(X_test)

if y_test.dtype == 'O':
    from sklearn.preprocessing import LabelEncoder
    le = LabelEncoder()
    y_test_encoded = le.fit_transform(y_test)
    y_pred_encoded = le.transform(y_pred)
else:
    y_test_encoded = y_test
    y_pred_encoded = y_pred

# Gráfico de dispersión
plt.figure(figsize=(8,6))
plt.scatter(y_test_encoded, y_pred_encoded, alpha=0.6, edgecolor='black')
plt.title(f"Predicciones vs Valores Reales (KNN con k={best_k})")
plt.xlabel("Valor Real")
plt.ylabel("Predicción del Modelo")
plt.grid(True, linestyle="--", alpha=0.5)

# Línea de referencia
max_val = max(max(y_test_encoded), max(y_pred_encoded))
plt.plot([0, max_val], [0, max_val], color='red', linestyle='--', label='Predicción Perfecta')
plt.legend()
plt.show()