# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FhIcU2BJZyubjzpQLb7UXgCTVFSct1V

# **Práctica 1: Data Cleaning**

Dataset obtenido de: [Video Game Sales](https://www.kaggle.com/datasets/gregorut/videogamesales)

Agregamos el path de el dataset
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("gregorut/videogamesales")

print("Path to dataset files:", path)

"""Obtener el nombre del archivo .csv que vamos a usar"""

import os
os.listdir(path)

"""Guardamos los datos en un df de pandas"""

import pandas as pd
df = pd.read_csv(os.path.join(path, "vgsales.csv"))

"""Visualizamos los 5 primeros datos"""

df.head()

"""**Limpieza de datos**

Información general del df
"""

df.info()

"""Estadísticas descriptivas"""

df.describe()

"""Verificamos si se encuentran valores duplicados"""

print(df.duplicated().sum())

"""No encontramos ningún valor duplicado.

Ahora verificamos si se encuentran valores nulos
"""

print(df.isnull().sum())

"""Como encontramos valores nulos, tomamos la descición de eliminarlos"""

df = df.dropna(subset=["Year", "Publisher"])

"""Corroboramos que se hayan eliminado."""

print(df.isnull().sum())

"""Volvemos a mostrar la información de nuestro dataframe"""

df.info()

"""Nos quedamos con solo los registros que no contengan valores nulos

Ahora hacemos la conversión de tipo de datos empezando por convertir 'Year' a tipo entero
"""

df["Year"] = df["Year"].astype(int)

"""Finalizamos con la limpieza de datos, ahora guardamos nuestro dataset limpio"""

df.to_csv("Video_Games_Sales_Cleaned.csv", index=False)

"""**Descarga del CSV limpio**"""

from google.colab import drive
drive.mount('/content/drive')