# -*- coding: utf-8 -*-
"""Data_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1si_9WZq-vCUsWyzbgHj_UOHf4g382ViN

# **Práctica 7: Data clustering**

Se carga el dataset, seleccionamos las variables numéricas relevantes y escalamos los datos
"""

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.read_csv("/content/Video_Games_Sales_Cleaned.csv")

features = ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

X = df[features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# Encontrar el número óptimo de clusters (método del codo)
Se busca el punto donde la curva empieza a “doblarse” (el codo).
Ese valor de k será el número ideal de clusters.
"""

inertia = []
K = range(1, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(8,5))
plt.plot(K, inertia, 'bo-')
plt.xlabel('Número de clusters (k)')
plt.ylabel('Inercia')
plt.title('Método del Codo para encontrar k óptimo')
plt.show()

"""La curva tiene un cambio pronunciado entre k = 1 y k = 3, y luego se vuelve más suave.

Eso indica que el número óptimo de clusters está alrededor de k = 3 o k = 4.

# Entrenar el modelo K-Means
Seleccionamos k = 3 como nuestro valor óptimo
"""

k_optimo = 3

kmeans = KMeans(n_clusters=k_optimo, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

print(df[['Name', 'Global_Sales', 'Cluster']].head())

"""# Visualizar los clusters
Visualizamos los clusters por medio de un gráfico comparando ventas en Norteamerica contra ventas en Europa
"""

plt.figure(figsize=(8,6))
sns.scatterplot(
    x='NA_Sales', y='EU_Sales',
    hue='Cluster', palette='Set2',
    data=df, alpha=0.7
)
plt.title('Clusters de Videojuegos (NA vs EU Sales)')
plt.xlabel('Ventas en Norteamérica')
plt.ylabel('Ventas en Europa')
plt.show()

"""# Analizar los clusters

"""

cluster_summary = df.groupby('Cluster')[features].mean()
print(cluster_summary)

"""Esto nos muestra la media de ventas por región en cada grupo encontrado por el algoritmo.

# Entrenar el modelo K-means
Ahora seleccionamos k = 4
"""

k_optimo = 4

kmeans = KMeans(n_clusters=k_optimo, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

print(df[['Name', 'Global_Sales', 'Cluster']].head())

"""# Visualizar los clusters"""

plt.figure(figsize=(8,6))
sns.scatterplot(
    x='NA_Sales', y='EU_Sales',
    hue='Cluster', palette='Set2',
    data=df, alpha=0.7
)
plt.title('Clusters de Videojuegos (NA vs EU Sales)')
plt.xlabel('Ventas en Norteamérica')
plt.ylabel('Ventas en Europa')
plt.show()

"""# Analizar los clusters"""

cluster_summary = df.groupby('Cluster')[features].mean()
print(cluster_summary)

"""# Interpretación de los datos
Ambos valores (k=3 o k=4) son razonables, con k=3 es más general y fácil de interpretar, mientras que con k=4 captura mejor los diferentes niveles de éxito comercial.
"""