# -*- coding: utf-8 -*-
"""PIA_Reporte.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fiQaslts9R7BNzCCdAKDAZ8qj50S5t1

# **Producto Integrador de Aprendizaje: Reporte**

Cargamos nuestro dataset limpio e importamos todas las librerías que vamos a utilizar
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.cluster import KMeans
from wordcloud import WordCloud

df = pd.read_csv("/content/Video_Games_Sales_Cleaned.csv")

"""**1. Estadísticas descriptivas**

a) Estadísticas descriptivas generales
"""

df.describe()

"""b) Frecuencia de géneros"""

df['Genre'].value_counts()

"""c) Frecuencia de plataformas"""

df['Platform'].value_counts()

"""**2. Agrupaciones por género**

a) Ventas globales promedio por género
"""

df.groupby("Genre")["Global_Sales"].mean().sort_values(ascending=False)

"""b) Ventas globales totales por género"""

df.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False)

"""**3. Modelos lineales y correlación**

a) Matriz de correlación
"""

plt.figure(figsize=(8,6))
sns.heatmap(df[['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']].corr(), annot=True, cmap="coolwarm")
plt.show()

"""b) Regresión lineal simple (NA_Sales -> Global_Sales)"""

X = df[['NA_Sales']]
y = df['Global_Sales']

model = LinearRegression()
model.fit(X, y)

r2 = model.score(X, y)
print("R2 Score:", r2)

y_pred = model.predict(X)

plt.figure(figsize=(10,6))
plt.scatter(X, y, alpha=0.5, label="Datos reales")
plt.plot(X, y_pred, linewidth=2, label="Línea de regresión")

plt.xlabel("NA_Sales (millones)")
plt.ylabel("Global_Sales (millones)")
plt.title("Regresión Lineal: NA_Sales → Global_Sales")
plt.legend()
plt.grid(True)
plt.show()

"""**4. Clasificación KNN**

a) Creación de etiquetas (ventas najas, medias, altas)
"""

df['Sales_Level'] = pd.qcut(df['Global_Sales'], q=3, labels=['Low','Medium','High'])

"""b) Entrenamiento en el modelo KNN"""

features = ['NA_Sales','EU_Sales','JP_Sales','Other_Sales']
X = df[features]
y = df['Sales_Level']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

"""**5. Clustering (K-Means)**

a) Método del codo
"""

inertia = []
K = range(1,11)

for k in K:
    model = KMeans(n_clusters=k, random_state=42)
    model.fit(X_scaled)
    inertia.append(model.inertia_)

plt.plot(K, inertia, marker='o')
plt.xlabel('k')
plt.ylabel('Inertia')
plt.title('Método del Codo')
plt.show()

"""b) Entrenamiento con el número óptimo de clusters"""

kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

df[['Name','Global_Sales','Cluster']].head()

"""**6. Forecasting (Series de tiempo con regresión lineal)**

a) Agrupar ventas por año
"""

df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df_yearly = df.groupby('Year')['Global_Sales'].sum().reset_index()

"""b) Entrenar el modelo"""

X = df_yearly[['Year']]
y = df_yearly['Global_Sales']

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

"""c) Pronóstico de los próximos 5 años"""

future_years = np.array(range(df_yearly['Year'].max()+1, df_yearly['Year'].max()+6)).reshape(-1,1)
future_pred = model.predict(future_years)

pd.DataFrame({'Year': future_years.flatten(), 'Forecast': future_pred})

"""**7. Nube de palabras (Text analysis)**

a) "Desde la columna Plataform"
"""

text = " ".join(df['Platform'].astype(str))

wordcloud = WordCloud(width=1200, height=600, background_color='white').generate(text)

plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

"""b) Desde la columna "Genre"
"""

text = " ".join(df['Genre'].astype(str))

wordcloud = WordCloud(width=1200, height=600, background_color='white').generate(text)

plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()