# -*- coding: utf-8 -*-
"""Descriptive_Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZf1reHEAt42b09S5O4YbhnWavY5gsnb

# **Práctica 2: Descriptive Statics**

Cargamos el dataset limpio
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Video_Games_Sales_Cleaned.csv")

"""Mostramos la información general"""

print(df.info())

"""Aseguramos que el dataset cargado es el limpio"""

print('filas duplicadas',df.duplicated().sum())
print(df.isnull().sum())

"""# Estadísticas descriptivas

Estadísticas de valores numéricos
"""

print(df.describe())

"""Estadísticas de valores categóricos"""

print(df.describe(include=['object', 'category']))

"""# Agrupamos los datos por entidades y obtener estadísticas

Ventas por género:
"""

genre_stats = df.groupby("Genre")["Global_Sales"].agg(["count", "sum", "mean", "max"]).sort_values("sum", ascending=False)
print(genre_stats)

"""Ventas por plataforma:"""

platform_stats = df.groupby("Platform")["Global_Sales"].agg(["count", "sum", "mean", "max"]).sort_values("sum", ascending=False)
print(platform_stats)

"""Ventas por publicador"""

publisher_stats = df.groupby("Publisher")["Global_Sales"].agg(["count", "sum", "mean", "max"]).sort_values("sum", ascending=False).head(20)
print(publisher_stats)

"""Ventas por año de lanzamiento"""

yearly_stats = df.groupby("Year")["Global_Sales"].agg(["count", "sum", "mean", "max"]).sort_index()
print(yearly_stats)