# -*- coding: utf-8 -*-
"""Statistic_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13z11Aqu1g5azh849HX6J9YKifusr3IIq

# **Práctica 4: Descriptive Statics**

Cargamos el dataset y filtramos datos válidos
"""

import pandas as pd
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols

df = pd.read_csv("Video_Games_Sales_Cleaned.csv")

df = df.dropna(subset=["Genre", "Global_Sales"])

"""**ANOVA (Análisis de Varianza)**

Queremos comprobar si las ventas globales son diferentes según el género
"""

anova_model = ols("Global_Sales ~ C(Genre)", data=df).fit()
anova_table = sm.stats.anova_lm(anova_model, typ=2)
print(anova_table)

"""El valor de 'p' se encuentra en la columna "PR(>F)" correspondiente a C(Genre)

En nuestro caso p = 1.33e-36, que es muchísimo menor que 0.05

Entonces concluimos que existen diferencias significativas en ventas entre los géneros.

**T-test (comparación de 2 grupos)**

Comparamos si las ventas globales de Action vs Sports son significativamente distintas
"""

# Subconjuntos
action_sales = df[df["Genre"] == "Action"]["Global_Sales"]
sports_sales = df[df["Genre"] == "Sports"]["Global_Sales"]

# T-test independiente
t_stat, p_val = stats.ttest_ind(action_sales, sports_sales, equal_var=False)
print("T-test Action vs Sports")
print("t =", t_stat, "p =", p_val)

"""Como p > 0.05,  no hay diferencia significativa entre ventas de Action y Sports.

**Kruskal-Wallis (prueba no paramétrica)**

Utilizamos las mismas variables para este método
"""

genres = ["Action", "Sports"]

samples = [df[df["Genre"] == g]["Global_Sales"] for g in genres]

h_stat, p_val = stats.kruskal(*samples)
print("Kruskal-Wallis para géneros Action, Sports")
print("H =", h_stat, "p =", p_val)

"""Como p < 0.05, al menos un género tiene ventas significativamente distintas respecto a los otros"""